dist: xenial

language: go

addons:
  snaps:
    - name: snapcraft
      classic: true

cache:
  directories: [$HOME/.cache/snapcraft/]

script:
  - openssl aes-256-cbc -K $encrypted_991c22bb09ad_key -iv $encrypted_991c22bb09ad_iv
    -in snapcraft-login.enc -out snapcraft-login -d
  - snapcraft login --with snapcraft-login
  - sudo apt update
  - ./scripts/snap.sh
  - sudo snap install *amd64*.snap --dangerous
  - ./tests/smoke_test.sh

deploy:
  'on':
    branch: master
  provider: script
  script: |
    snapcraft login --with snapcraft-login
    for file in *.snap; do echo 'file: ' \$file && snapcraft push \$file --release edge; done
  skip_cleanup: true
