sudo: required

services:
  - docker

cache:
  directories: [$HOME/.cache/snapcraft/]

script:
  - openssl aes-256-cbc -K $encrypted_85c400651e0f_key -iv $encrypted_85c400651e0f_iv
    -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
  - ./scripts/snap-in-docker.sh
  - sudo apt update
  - sudo apt install snapd
  - sudo snap install *amd64*.snap --dangerous
  - ./tests/smoke_test.sh

deploy:
  'on':
    branch: master
  provider: script
  script: ./scripts/push-in-docker.sh
  skip_cleanup: true
