dist: xenial

language: minimal

arch:
  - amd64
  - arm64

cache:
  directories: [$HOME/.cache/snapcraft/]

script:
  - until sudo snap install snapcraft --classic; do echo "Retrying"; done
  - openssl aes-256-cbc -K $encrypted_991c22bb09ad_key -iv $encrypted_991c22bb09ad_iv
    -in snapcraft-login.enc -out snapcraft-login -d
  - snapcraft login --with snapcraft-login
  - sudo apt update
  - sudo apt install jq
  - ./scripts/snap.sh
  - sudo snap install *.snap --dangerous
  - ./tests/smoke_test.sh
  - |
    if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then
      for file in *.snap; do echo 'file: ' $file && snapcraft push $file --release edge; done
    fi
