name: ipfs
version: master
summary: global, versioned, peer-to-peer filesystem
description: |
  IPFS combines good ideas from Git, BitTorrent, Kademlia, SFS, and the Web.
  It is like a single bittorrent swarm, exchanging git objects. IPFS provides
  an interface as simple as the HTTP web, but with permanence built in. You
  can also mount the world at /ipfs.

confinement: strict

apps:
  ipfs:
    command: ipfs
    plugs: [home, network, network-bind, removable-media]

parts:
  ipfs:
    source: https://github.com/ipfs/go-ipfs.git
    source-tag: master
    plugin: nil
    build-packages: [make, wget]
    prepare: |
      mkdir -p ../go/src/github.com/ipfs/go-ipfs
      cp -R . ../go/src/github.com/ipfs/go-ipfs
    build: |
      env GOPATH=$(pwd)/../go make -C ../go/src/github.com/ipfs/go-ipfs deps
      env GOPATH=$(pwd)/../go CC=$ARCH_TRIPLET-gcc CXX=$ARCH_TRIPLET-g++ CGO_ENABLED=1 GOARCH=$TARGET_GOARCH make -C ../go/src/github.com/ipfs/go-ipfs install
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      for file in $(find ../go/bin/ -type f); do
          mv $file $SNAPCRAFT_PART_INSTALL/bin/
      done
    after: [go]
  go:
    source-tag: go1.8.3
